version: '3'
services:

  traefik:
      image: "traefik:v2.6.6"
      container_name: "traefik-network"
      command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --api
      - --log.level=DEBUG
      - --certificatesresolvers.letsencrypt.acme.email=felipeng.eletrica@gmail.com
      - --certificatesresolvers.letsencrypt.acme.storage=/acme.json
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      ports:
        - "80:80"
        - "443:443"
      networks:
        - internal
        - web

      volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "./acme.json:/acme.json"
      labels:
            # Dashboard
            - "traefik.http.routers.traefik.rule=Host(`dashboard.localhost`)"
            - "traefik.http.routers.traefik.service=api@internal"
            - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
            - "traefik.http.routers.traefik.entrypoints=websecure"
            - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
            - "traefik.http.routers.http-catchall.entrypoints=web"
            - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
            - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  apache:
    image: 'bitnami/apache:latest'
    container_name: apache-network
    ports:
      - '8080:8080'
    volumes:
      - ./app:/app
    
    labels:
       - traefik.http.routers.apache.rule=Host(`apache.localhost`)
       - traefik.http.routers.apache.tls=true
       - traefik.http.routers.apache.tls.certresolver=lets-encryp
       - traefik.port=8080
    networks:
      - internal
      - web
    restart: unless-stopped

  grafana:
      image: grafana/grafana:latest
      container_name: grafana-network
      #user: "$UID:$GID"
      user: "104"

      volumes:
      - ./grafana_data:/var/lib/grafana

      expose:
        - 3002
      ports:
        - 3002:3002
      
      labels:
        - traefik.http.routers.grafana.rule=Host(`grafana.localhost`)
        - traefik.http.routers.grafana.service=grafana-network
        - traefik.http.routers.grafana.tls=true
        - traefik.http.routers.grafana.tls.certresolver=lets-encryp}
        - traefik.port=3002

      networks:
        - internal
        - web

      environment: 
        - GF_SERVER_HTTP_PORT=3002
        - GF_SERVER_PROTOCOL=http
        - GF_SERVER_DOMAIN=grafana.localhost
        - GF_SERVER_ROOT_URL=https://grafana.localhost:443
        #- GF_SERVER_ROOT_URL=http://localhost:8181/grafana/
        - GF_SERVER_SERVE_FROM_SUB_PATH=true
       

      restart: unless-stopped

volumes:
  grafana_data:

networks:
  web:
    external: true
  internal:
    external: false